### ISSUE TITLE
Write inventory directly from Terraform

### ISSUE THREAD

**Issue by backstreetkiwi** [observabilitystack/workshop-cluster#10]
Discussion welcome!
As there is no Linux dpkg version for `terraform-inventory`, I find it easier to use the straight-forward approach of writing the inventory file from Terraform.

**Comment by tboeghk** [comment]
This is absolutely doable if you have servers alike. If you have different server roles, this approach loses those. I'd somehow suggest to stay with `terraform-inventory`.

**Comment by backstreetkiwi** [comment]
Okay, I keep that change on "my" branch with my settings and I look into it later. No worries.
